name: my-blog-api

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_URL=${DB_URL}
      - TEST_DB_URL=${TEST_DB_URL}
