name: my-blog-db

services:
  pg:
    image: postgres:15.3-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./volumes/databases/pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  test-pg:
    image: postgres:15.3-alpine
    ports:
      - "${TEST_DB_PORT}:5432"
    volumes:
      - ./volumes/databases/test-pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
